from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(825, 431)
        self.b1 = QtWidgets.QPushButton(Dialog)
        self.b1.setGeometry(QtCore.QRect(0, 110, 71, 41))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Dialog)
        self.b2.setGeometry(QtCore.QRect(70, 110, 61, 41))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Dialog)
        self.b3.setGeometry(QtCore.QRect(130, 110, 61, 41))
        self.b3.setObjectName("b3")
        self.b7 = QtWidgets.QPushButton(Dialog)
        self.b7.setGeometry(QtCore.QRect(390, 110, 71, 41))
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(Dialog)
        self.b8.setGeometry(QtCore.QRect(460, 110, 71, 41))
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(Dialog)
        self.b9.setGeometry(QtCore.QRect(530, 110, 71, 41))
        self.b9.setObjectName("b9")
        self.b10 = QtWidgets.QPushButton(Dialog)
        self.b10.setGeometry(QtCore.QRect(600, 110, 81, 41))
        self.b10.setObjectName("b10")
        self.b4 = QtWidgets.QPushButton(Dialog)
        self.b4.setGeometry(QtCore.QRect(190, 110, 61, 41))
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(Dialog)
        self.b5.setGeometry(QtCore.QRect(250, 110, 71, 41))
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(Dialog)
        self.b6.setGeometry(QtCore.QRect(320, 110, 71, 41))
        self.b6.setObjectName("b6")
        self.b14 = QtWidgets.QPushButton(Dialog)
        self.b14.setGeometry(QtCore.QRect(70, 150, 61, 41))
        self.b14.setObjectName("b14")
        self.b20 = QtWidgets.QPushButton(Dialog)
        self.b20.setGeometry(QtCore.QRect(460, 150, 71, 41))
        self.b20.setObjectName("b20")
        self.b15 = QtWidgets.QPushButton(Dialog)
        self.b15.setGeometry(QtCore.QRect(130, 150, 61, 41))
        self.b15.setObjectName("b15")
        self.b21 = QtWidgets.QPushButton(Dialog)
        self.b21.setGeometry(QtCore.QRect(530, 150, 71, 41))
        self.b21.setObjectName("b21")
        self.b12 = QtWidgets.QPushButton(Dialog)
        self.b12.setGeometry(QtCore.QRect(750, 110, 81, 41))
        self.b12.setObjectName("b12")
        self.b11 = QtWidgets.QPushButton(Dialog)
        self.b11.setGeometry(QtCore.QRect(680, 110, 71, 41))
        self.b11.setObjectName("b11")
        self.b22 = QtWidgets.QPushButton(Dialog)
        self.b22.setGeometry(QtCore.QRect(600, 150, 81, 41))
        self.b22.setObjectName("b22")
        self.b17 = QtWidgets.QPushButton(Dialog)
        self.b17.setGeometry(QtCore.QRect(250, 150, 71, 41))
        self.b17.setObjectName("b17")
        self.b18 = QtWidgets.QPushButton(Dialog)
        self.b18.setGeometry(QtCore.QRect(320, 150, 71, 41))
        self.b18.setObjectName("b18")
        self.b19 = QtWidgets.QPushButton(Dialog)
        self.b19.setGeometry(QtCore.QRect(390, 150, 71, 41))
        self.b19.setObjectName("b19")
        self.b49 = QtWidgets.QPushButton(Dialog)
        self.b49.setGeometry(QtCore.QRect(750, 230, 81, 41))
        self.b49.setObjectName("b49")
        self.b37 = QtWidgets.QPushButton(Dialog)
        self.b37.setGeometry(QtCore.QRect(750, 190, 81, 41))
        self.b37.setObjectName("b37")
        self.b61 = QtWidgets.QPushButton(Dialog)
        self.b61.setGeometry(QtCore.QRect(750, 270, 81, 41))
        self.b61.setObjectName("b61")
        self.b31 = QtWidgets.QPushButton(Dialog)
        self.b31.setGeometry(QtCore.QRect(320, 190, 71, 41))
        self.b31.setObjectName("b31")
        self.b34 = QtWidgets.QPushButton(Dialog)
        self.b34.setGeometry(QtCore.QRect(530, 190, 71, 41))
        self.b34.setObjectName("b34")
        self.b30 = QtWidgets.QPushButton(Dialog)
        self.b30.setGeometry(QtCore.QRect(250, 190, 71, 41))
        self.b30.setObjectName("b30")
        self.b24 = QtWidgets.QPushButton(Dialog)
        self.b24.setGeometry(QtCore.QRect(750, 150, 81, 41))
        self.b24.setObjectName("b24")
        self.b13 = QtWidgets.QPushButton(Dialog)
        self.b13.setGeometry(QtCore.QRect(0, 150, 71, 41))
        self.b13.setObjectName("b13")
        self.b48 = QtWidgets.QPushButton(Dialog)
        self.b48.setGeometry(QtCore.QRect(680, 230, 71, 41))
        self.b48.setObjectName("b48")
        self.b46 = QtWidgets.QPushButton(Dialog)
        self.b46.setGeometry(QtCore.QRect(530, 230, 71, 41))
        self.b46.setObjectName("b46")
        self.b56 = QtWidgets.QPushButton(Dialog)
        self.b56.setGeometry(QtCore.QRect(390, 270, 71, 41))
        self.b56.setObjectName("b56")
        self.b32 = QtWidgets.QPushButton(Dialog)
        self.b32.setGeometry(QtCore.QRect(390, 190, 71, 41))
        self.b32.setObjectName("b32")
        self.b36 = QtWidgets.QPushButton(Dialog)
        self.b36.setGeometry(QtCore.QRect(680, 190, 71, 41))
        self.b36.setObjectName("b36")
        self.b23 = QtWidgets.QPushButton(Dialog)
        self.b23.setGeometry(QtCore.QRect(680, 150, 71, 41))
        self.b23.setObjectName("b23")
        self.b29 = QtWidgets.QPushButton(Dialog)
        self.b29.setGeometry(QtCore.QRect(190, 190, 61, 41))
        self.b29.setObjectName("b29")
        self.b27 = QtWidgets.QPushButton(Dialog)
        self.b27.setGeometry(QtCore.QRect(70, 190, 61, 41))
        self.b27.setObjectName("b27")
        self.b35 = QtWidgets.QPushButton(Dialog)
        self.b35.setGeometry(QtCore.QRect(600, 190, 81, 41))
        self.b35.setObjectName("b35")
        self.b47 = QtWidgets.QPushButton(Dialog)
        self.b47.setGeometry(QtCore.QRect(600, 230, 81, 41))
        self.b47.setObjectName("b47")
        self.b28 = QtWidgets.QPushButton(Dialog)
        self.b28.setGeometry(QtCore.QRect(130, 190, 61, 41))
        self.b28.setObjectName("b28")
        self.b25 = QtWidgets.QPushButton(Dialog)
        self.b25.setGeometry(QtCore.QRect(0, 190, 75, 41))
        self.b25.setObjectName("b25")
        self.b16 = QtWidgets.QPushButton(Dialog)
        self.b16.setGeometry(QtCore.QRect(190, 150, 61, 41))
        self.b16.setObjectName("b16")
        self.b41 = QtWidgets.QPushButton(Dialog)
        self.b41.setGeometry(QtCore.QRect(190, 230, 61, 41))
        self.b41.setObjectName("b41")
        self.b42 = QtWidgets.QPushButton(Dialog)
        self.b42.setGeometry(QtCore.QRect(250, 230, 71, 41))
        self.b42.setObjectName("b42")
        self.b62 = QtWidgets.QPushButton(Dialog)
        self.b62.setGeometry(QtCore.QRect(0, 310, 71, 41))
        self.b62.setObjectName("b62")
        self.b44 = QtWidgets.QPushButton(Dialog)
        self.b44.setGeometry(QtCore.QRect(390, 230, 71, 41))
        self.b44.setObjectName("b44")
        self.b45 = QtWidgets.QPushButton(Dialog)
        self.b45.setGeometry(QtCore.QRect(460, 230, 71, 41))
        self.b45.setObjectName("b45")
        self.b33 = QtWidgets.QPushButton(Dialog)
        self.b33.setGeometry(QtCore.QRect(460, 190, 71, 41))
        self.b33.setObjectName("b33")
        self.b60 = QtWidgets.QPushButton(Dialog)
        self.b60.setGeometry(QtCore.QRect(680, 270, 71, 41))
        self.b60.setObjectName("b60")
        self.b39 = QtWidgets.QPushButton(Dialog)
        self.b39.setGeometry(QtCore.QRect(70, 230, 61, 41))
        self.b39.setObjectName("b39")
        self.b55 = QtWidgets.QPushButton(Dialog)
        self.b55.setGeometry(QtCore.QRect(320, 270, 71, 41))
        self.b55.setObjectName("b55")
        self.b40 = QtWidgets.QPushButton(Dialog)
        self.b40.setGeometry(QtCore.QRect(130, 230, 61, 41))
        self.b40.setObjectName("b40")
        self.b51 = QtWidgets.QPushButton(Dialog)
        self.b51.setGeometry(QtCore.QRect(70, 270, 61, 41))
        self.b51.setObjectName("b51")
        self.b53 = QtWidgets.QPushButton(Dialog)
        self.b53.setGeometry(QtCore.QRect(190, 270, 61, 41))
        self.b53.setObjectName("b53")
        self.b73 = QtWidgets.QPushButton(Dialog)
        self.b73.setGeometry(QtCore.QRect(750, 310, 81, 41))
        self.b73.setObjectName("b73")
        self.b54 = QtWidgets.QPushButton(Dialog)
        self.b54.setGeometry(QtCore.QRect(250, 270, 71, 41))
        self.b54.setObjectName("b54")
        self.b50 = QtWidgets.QPushButton(Dialog)
        self.b50.setGeometry(QtCore.QRect(0, 270, 71, 41))
        self.b50.setObjectName("b50")
        self.b72 = QtWidgets.QPushButton(Dialog)
        self.b72.setGeometry(QtCore.QRect(680, 310, 71, 41))
        self.b72.setObjectName("b72")
        self.b38 = QtWidgets.QPushButton(Dialog)
        self.b38.setGeometry(QtCore.QRect(0, 230, 75, 41))
        self.b38.setObjectName("b38")
        self.b52 = QtWidgets.QPushButton(Dialog)
        self.b52.setGeometry(QtCore.QRect(130, 270, 61, 41))
        self.b52.setObjectName("b52")
        self.b58 = QtWidgets.QPushButton(Dialog)
        self.b58.setGeometry(QtCore.QRect(530, 270, 71, 41))
        self.b58.setObjectName("b58")
        self.b63 = QtWidgets.QPushButton(Dialog)
        self.b63.setGeometry(QtCore.QRect(70, 310, 61, 41))
        self.b63.setObjectName("b63")
        self.b59 = QtWidgets.QPushButton(Dialog)
        self.b59.setGeometry(QtCore.QRect(600, 270, 81, 41))
        self.b59.setObjectName("b59")
        self.b67 = QtWidgets.QPushButton(Dialog)
        self.b67.setGeometry(QtCore.QRect(320, 310, 71, 41))
        self.b67.setObjectName("b67")
        self.b64 = QtWidgets.QPushButton(Dialog)
        self.b64.setGeometry(QtCore.QRect(130, 310, 61, 41))
        self.b64.setObjectName("b64")
        self.b65 = QtWidgets.QPushButton(Dialog)
        self.b65.setGeometry(QtCore.QRect(190, 310, 61, 41))
        self.b65.setObjectName("b65")
        self.b57 = QtWidgets.QPushButton(Dialog)
        self.b57.setGeometry(QtCore.QRect(460, 270, 71, 41))
        self.b57.setObjectName("b57")
        self.b66 = QtWidgets.QPushButton(Dialog)
        self.b66.setGeometry(QtCore.QRect(250, 310, 71, 41))
        self.b66.setObjectName("b66")
        self.b84 = QtWidgets.QPushButton(Dialog)
        self.b84.setGeometry(QtCore.QRect(680, 350, 71, 41))
        self.b84.setObjectName("b84")
        self.b85 = QtWidgets.QPushButton(Dialog)
        self.b85.setGeometry(QtCore.QRect(750, 350, 81, 41))
        self.b85.setObjectName("b85")
        self.backspace_button = QtWidgets.QPushButton(Dialog)
        self.backspace_button.setGeometry(QtCore.QRect(700, 60, 131, 51))
        self.backspace_button.setObjectName("backspace_button")
        font = QtGui.QFont()
        font.setPointSize(23)
        
       
        self.b68 = QtWidgets.QPushButton(Dialog)
        self.b68.setGeometry(QtCore.QRect(390, 310, 71, 41))
        self.b68.setObjectName("b68")
        self.b71 = QtWidgets.QPushButton(Dialog)
        self.b71.setGeometry(QtCore.QRect(600, 310, 81, 41))
        self.b71.setObjectName("b71")
        self.b78 = QtWidgets.QPushButton(Dialog)
        self.b78.setGeometry(QtCore.QRect(250, 350, 71, 41))
        self.b78.setObjectName("b78")
        self.b77 = QtWidgets.QPushButton(Dialog)
        self.b77.setGeometry(QtCore.QRect(190, 350, 61, 41))
        self.b77.setObjectName("b77")
        self.b70 = QtWidgets.QPushButton(Dialog)
        self.b70.setGeometry(QtCore.QRect(530, 310, 71, 41))
        self.b70.setObjectName("b70")
        self.b69 = QtWidgets.QPushButton(Dialog)
        self.b69.setGeometry(QtCore.QRect(460, 310, 71, 41))
        self.b69.setObjectName("b69")
        self.b76 = QtWidgets.QPushButton(Dialog)
        self.b76.setGeometry(QtCore.QRect(130, 350, 61, 41))
        self.b76.setObjectName("b76")
        self.b75 = QtWidgets.QPushButton(Dialog)
        self.b75.setGeometry(QtCore.QRect(70, 350, 61, 41))
        self.b75.setObjectName("b75")
        self.b79 = QtWidgets.QPushButton(Dialog)
        self.b79.setGeometry(QtCore.QRect(320, 350, 71, 41))
        self.b79.setObjectName("b79")
        self.b74 = QtWidgets.QPushButton(Dialog)
        self.b74.setGeometry(QtCore.QRect(0, 350, 71, 41))
        self.b74.setObjectName("b74")
        self.b82 = QtWidgets.QPushButton(Dialog)
        self.b82.setGeometry(QtCore.QRect(530, 350, 71, 41))
        self.b82.setObjectName("b82")
        self.b81 = QtWidgets.QPushButton(Dialog)
        self.b81.setGeometry(QtCore.QRect(460, 350, 71, 41))
        self.b81.setObjectName("b81")
        self.b83 = QtWidgets.QPushButton(Dialog)
        self.b83.setGeometry(QtCore.QRect(600, 350, 81, 41))
        self.b83.setObjectName("b83")
        self.b80 = QtWidgets.QPushButton(Dialog)
        self.b80.setGeometry(QtCore.QRect(390, 350, 71, 41))
        self.b80.setObjectName("b80")
        self.b94 = QtWidgets.QPushButton(Dialog)
        self.b94.setGeometry(QtCore.QRect(530, 390, 71, 41))
        self.b94.setObjectName("b94")
        self.b89 = QtWidgets.QPushButton(Dialog)
        self.b89.setGeometry(QtCore.QRect(190, 390, 61, 41))
        self.b89.setObjectName("b89")
        self.b88 = QtWidgets.QPushButton(Dialog)
        self.b88.setGeometry(QtCore.QRect(130, 390, 61, 41))
        self.b88.setObjectName("b88")
        self.b87 = QtWidgets.QPushButton(Dialog)
        self.b87.setGeometry(QtCore.QRect(70, 390, 61, 41))
        self.b87.setObjectName("b87")
        self.b95 = QtWidgets.QPushButton(Dialog)
        self.b95.setGeometry(QtCore.QRect(600, 390, 81, 41))
        self.b95.setObjectName("b95")
        self.b93 = QtWidgets.QPushButton(Dialog)
        self.b93.setGeometry(QtCore.QRect(460, 390, 71, 41))
        self.b93.setObjectName("b93")
        self.b96 = QtWidgets.QPushButton(Dialog)
        self.b96.setGeometry(QtCore.QRect(680, 390, 71, 41))
        self.b96.setObjectName("b96")
        self.b86 = QtWidgets.QPushButton(Dialog)
        self.b86.setGeometry(QtCore.QRect(0, 390, 71, 41))
        self.b86.setObjectName("b86")
        self.b91 = QtWidgets.QPushButton(Dialog)
        self.b91.setGeometry(QtCore.QRect(320, 390, 71, 41))
        self.b91.setObjectName("b91")
        self.b26 = QtWidgets.QPushButton(Dialog)
        self.b26.setGeometry(QtCore.QRect(750, 390, 81, 41))
        self.b26.setObjectName("b26")
        self.b90 = QtWidgets.QPushButton(Dialog)
        self.b90.setGeometry(QtCore.QRect(250, 390, 71, 41))
        self.b90.setObjectName("b90")
        self.b92 = QtWidgets.QPushButton(Dialog)
        self.b92.setGeometry(QtCore.QRect(390, 390, 71, 41))
        self.b92.setObjectName("b92")
        self.b43 = QtWidgets.QPushButton(Dialog)
        self.b43.setGeometry(QtCore.QRect(320, 230, 71, 41))
        self.b43.setObjectName("b43")

        
        self.l1 = QtWidgets.QLineEdit(Dialog)
        self.l1.setGeometry(QtCore.QRect(220, 30, 331, 61))
        self.l1.setObjectName("l1")
        self.l1.setReadOnly(True)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.l1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))

        


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Connecting the buttons to their respective functions
        self.b1.clicked.connect(self.show_b1)
        self.b2.clicked.connect(self.print_b2)
        self.b3.clicked.connect(self.print_b3)
        self.b4.clicked.connect(self.print_b4)
        self.b5.clicked.connect(self.print_b5)
        self.b6.clicked.connect(self.print_b6)
        self.b7.clicked.connect(self.print_b7)
       
        self.b8.clicked.connect(self.print_b8)
        self.b9.clicked.connect(self.print_b9)
        self.b10.clicked.connect(self.print_b10)
        self.b11.clicked.connect(self.print_b11)
        self.b12.clicked.connect(self.print_b12)
        self.b13.clicked.connect(self.print_b13)
        self.b14.clicked.connect(self.print_b14)
        self.b15.clicked.connect(self.print_b15)
        self.b16.clicked.connect(self.print_b16)
        self.b17.clicked.connect(self.print_b17)
        self.b18.clicked.connect(self.print_b18)
        self.b19.clicked.connect(self.print_b19)
        self.b20.clicked.connect(self.print_b20)
        self.b21.clicked.connect(self.print_b21)
        self.b22.clicked.connect(self.print_b22)
        self.b23.clicked.connect(self.print_b23)
        self.b24.clicked.connect(self.print_b24)
        self.b25.clicked.connect(self.print_b25)
        self.b26.clicked.connect(self.print_b26)
        self.b27.clicked.connect(self.print_b27)
        self.b28.clicked.connect(self.print_b28)
        self.b29.clicked.connect(self.print_b29)
        self.b30.clicked.connect(self.print_b30)
        self.b31.clicked.connect(self.print_b31)
        self.b32.clicked.connect(self.print_b32)
        self.b33.clicked.connect(self.print_b33)
        self.b34.clicked.connect(self.print_b34)
        self.b35.clicked.connect(self.print_b35)
        self.b36.clicked.connect(self.print_b36)
        self.b37.clicked.connect(self.print_b37)
        self.b38.clicked.connect(self.print_b38)
        self.b39.clicked.connect(self.print_b39)
        self.b40.clicked.connect(self.print_b40)
        self.b41.clicked.connect(self.print_b41)
        self.b42.clicked.connect(self.print_b42)
        self.b43.clicked.connect(self.print_b43)
        self.b44.clicked.connect(self.print_b44)
        self.b45.clicked.connect(self.print_b45)
        self.b46.clicked.connect(self.print_b46)
        self.b47.clicked.connect(self.print_b47)
        self.b48.clicked.connect(self.print_b48)
        self.b49.clicked.connect(self.print_b49)
        self.b50.clicked.connect(self.print_b50)
        self.b51.clicked.connect(self.print_b51)
        self.b52.clicked.connect(self.print_b52)
        self.b53.clicked.connect(self.print_b53)
        self.b54.clicked.connect(self.print_b54)
        self.b55.clicked.connect(self.print_b55)
        self.b56.clicked.connect(self.print_b56)
        self.b57.clicked.connect(self.print_b57)
        self.b58.clicked.connect(self.print_b58)
        self.b59.clicked.connect(self.print_b59)
        self.b60.clicked.connect(self.print_b60)
        self.b61.clicked.connect(self.print_b61)
        self.b62.clicked.connect(self.print_b62)
        self.b63.clicked.connect(self.print_b63)
        self.b64.clicked.connect(self.print_b64)
        self.b65.clicked.connect(self.print_b65)
        self.b66.clicked.connect(self.print_b66)
        self.b67.clicked.connect(self.print_b67)
        self.b68.clicked.connect(self.print_b68)
        self.b69.clicked.connect(self.print_b69)
        self.b70.clicked.connect(self.print_b70)
        self.b71.clicked.connect(self.print_b71)
        self.b72.clicked.connect(self.print_b72)
        self.b73.clicked.connect(self.print_b73)
        self.b74.clicked.connect(self.print_b74)
        self.b75.clicked.connect(self.print_b75)
        self.b76.clicked.connect(self.print_b76)
        self.b77.clicked.connect(self.print_b77)
        self.b78.clicked.connect(self.print_b78)
        self.b79.clicked.connect(self.print_b79)
        self.b80.clicked.connect(self.print_b80)
        self.b81.clicked.connect(self.print_b81)
        self.b82.clicked.connect(self.print_b82)
        self.b83.clicked.connect(self.print_b83)
        self.b84.clicked.connect(self.print_b84)
        self.b85.clicked.connect(self.print_b85)
        self.b86.clicked.connect(self.print_b86)
        self.b87.clicked.connect(self.print_b87)
        self.b88.clicked.connect(self.print_b88)
        self.b89.clicked.connect(self.print_b89)
        self.b90.clicked.connect(self.print_b90)
        self.b91.clicked.connect(self.print_b91)
        self.b92.clicked.connect(self.print_b92)
        self.b93.clicked.connect(self.print_b93)
        self.b94.clicked.connect(self.print_b94)
        self.b95.clicked.connect(self.print_b95)
        self.b96.clicked.connect(self.print_b96)
        
        self.backspace_button.clicked.connect(self.backspace)

        self.backspace_button.pressed.connect(self.start_backspace_timer)
        self.backspace_button.released.connect(self.stop_backspace_timer)


        self.backspace_timer = QtCore.QTimer()
        self.backspace_timer.setSingleShot(True)
        self.backspace_timer.timeout.connect(self.clear_text)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SciKey (v.0.0.1)"))
        Dialog.setWindowIcon(QIcon("ok.png"))
        self.b1.setText(_translate("Dialog", "+"))
        self.b2.setText(_translate("Dialog", "-"))
        self.b3.setText(_translate("Dialog", "*"))
        self.b7.setText(_translate("Dialog", "<"))
        self.b8.setText(_translate("Dialog", "("))
        self.b9.setText(_translate("Dialog", ")"))
        self.b10.setText(_translate("Dialog", "{"))
        self.b4.setText(_translate("Dialog", "/"))
        self.b5.setText(_translate("Dialog", "="))
        self.b6.setText(_translate("Dialog", ">"))
        self.b14.setText(_translate("Dialog", "["))
        self.b20.setText(_translate("Dialog", "≈"))
        self.b15.setText(_translate("Dialog", "]"))
        self.b21.setText(_translate("Dialog", "≤"))
        self.b12.setText(_translate("Dialog", "%"))
        self.b11.setText(_translate("Dialog", "}"))
        self.b22.setText(_translate("Dialog", "≥"))
        self.b17.setText(_translate("Dialog", "^"))
        self.b18.setText(_translate("Dialog", "~"))
        self.b19.setText(_translate("Dialog", "≠"))
        self.b49.setText(_translate("Dialog", "∃"))
        self.b37.setText(_translate("Dialog", "⊂"))
        self.b61.setText(_translate("Dialog", "∪"))
        self.b31.setText(_translate("Dialog", "∜"))
        self.b34.setText(_translate("Dialog", "¬"))
        self.b30.setText(_translate("Dialog", "∛"))
        self.b24.setText(_translate("Dialog", "!"))
        self.b13.setText(_translate("Dialog", "⊃"))
        self.b48.setText(_translate("Dialog", "∀"))
        self.b46.setText(_translate("Dialog", "→"))
        self.b56.setText(_translate("Dialog", "≡"))
        self.b32.setText(_translate("Dialog", "x_y"))
        self.b36.setText(_translate("Dialog", "∉"))
        self.b23.setText(_translate("Dialog", "∞"))
        self.b29.setText(_translate("Dialog", "√"))
        self.b27.setText(_translate("Dialog", "±"))
        self.b35.setText(_translate("Dialog", "∈"))
        self.b47.setText(_translate("Dialog", "↔"))
        self.b28.setText(_translate("Dialog", "∩"))
        self.b25.setText(_translate("Dialog", "∴"))
        self.b16.setText(_translate("Dialog", "⊥"))
        self.b41.setText(_translate("Dialog", "d/dx"))
        self.b42.setText(_translate("Dialog", "∂/∂x"))
        self.b62.setText(_translate("Dialog", "∫"))
        self.b44.setText(_translate("Dialog", "∬"))
        self.b45.setText(_translate("Dialog", "∭"))
        self.b33.setText(_translate("Dialog", "Σ"))
        self.b60.setText(_translate("Dialog", "Π"))
        self.b39.setText(_translate("Dialog", "cos"))
        self.b55.setText(_translate("Dialog", "arctan"))
        self.b40.setText(_translate("Dialog", "tan"))
        self.b51.setText(_translate("Dialog", "sec"))
        self.b53.setText(_translate("Dialog", "arcsin"))
        self.b73.setText(_translate("Dialog", "∠"))
        self.b54.setText(_translate("Dialog", "arccos"))
        self.b50.setText(_translate("Dialog", "csc"))
        self.b72.setText(_translate("Dialog", "∝"))
        self.b38.setText(_translate("Dialog", "sin"))
        self.b52.setText(_translate("Dialog", "cot"))
        self.b58.setText(_translate("Dialog", "∥"))
        self.b63.setText(_translate("Dialog", "↑"))
        self.b59.setText(_translate("Dialog", "⇌"))
        self.b67.setText(_translate("Dialog", "ln"))
        self.b64.setText(_translate("Dialog", "↓"))
        self.b65.setText(_translate("Dialog", "pH"))
        self.b57.setText(_translate("Dialog", "°"))
        self.b66.setText(_translate("Dialog", "log"))
        self.b84.setText(_translate("Dialog", "e"))
        self.b85.setText(_translate("Dialog", "π"))
        self.backspace_button.setText(_translate("Dialog", "<= clear"))
        self.l1.setText(_translate("Dialog", "Type..."))
        self.b68.setText(_translate("Dialog", "Δ"))
        self.b71.setText(_translate("Dialog", "γ"))
        self.b78.setText(_translate("Dialog", "θ"))
        self.b77.setText(_translate("Dialog", "η"))
        self.b70.setText(_translate("Dialog", "β"))
        self.b69.setText(_translate("Dialog", "α"))
        self.b76.setText(_translate("Dialog", "ζ"))
        self.b75.setText(_translate("Dialog", "ε"))
        self.b79.setText(_translate("Dialog", "ι"))
        self.b74.setText(_translate("Dialog", "δ"))
        self.b82.setText(_translate("Dialog", "μ"))
        self.b81.setText(_translate("Dialog", "λ"))
        self.b83.setText(_translate("Dialog", "ν"))
        self.b80.setText(_translate("Dialog", "κ"))
        self.b94.setText(_translate("Dialog", "ψ"))
        self.b89.setText(_translate("Dialog", "τ"))
        self.b88.setText(_translate("Dialog", "σ"))
        self.b87.setText(_translate("Dialog", "ω"))
        self.b95.setText(_translate("Dialog", "Ω"))
        self.b93.setText(_translate("Dialog", "χ"))
        self.b96.setText(_translate("Dialog", "|"))
        self.b86.setText(_translate("Dialog", "ξ"))
        self.b91.setText(_translate("Dialog", "φ"))
        self.b26.setText(_translate("Dialog", "⇉"))
        self.b90.setText(_translate("Dialog", "υ"))
        self.b92.setText(_translate("Dialog", "Φ"))
        self.b43.setText(_translate("Dialog", "△"))

    def show_b1(self):
        self.l1.setText(self.l1.text() + "+")
          # Append "a" to the existing text
    def print_b2(self):
        self.l1.setText(self.l1.text() + "-")
    def print_b3(self):
        self.l1.setText(self.l1.text() + "*")
    def print_b4(self):
        self.l1.setText(self.l1.text() + "/")
    def print_b5(self):
        self.l1.setText(self.l1.text() + "=")
    def print_b6(self):
        self.l1.setText(self.l1.text() + ">")
    def print_b7(self):
        self.l1.setText(self.l1.text() + ">")
    def print_b7(self):
        self.l1.setText(self.l1.text() + "<")
    def print_b8(self):
        self.l1.setText(self.l1.text() + "(")
    def print_b9(self):
        self.l1.setText(self.l1.text() + ")")
    def print_b10(self):
        self.l1.setText(self.l1.text() + "{")
    def print_b11(self):
        self.l1.setText(self.l1.text() + "}")
    def print_b12(self):
        self.l1.setText(self.l1.text() + "%")
    def print_b13(self):
        self.l1.setText(self.l1.text() + "⊃")
    def print_b14(self):
        self.l1.setText(self.l1.text() + "[")
    def print_b15(self):
        self.l1.setText(self.l1.text() + "]")
    def print_b16(self):
        self.l1.setText(self.l1.text() + "⊥")
    def print_b17(self):
        self.l1.setText(self.l1.text() + "^")
    def print_b18(self):
        self.l1.setText(self.l1.text() + "~")
    def print_b19(self):
        self.l1.setText(self.l1.text() + "≠")
    def print_b20(self):
        self.l1.setText(self.l1.text() + "≈")
    def print_b21(self):
        self.l1.setText(self.l1.text() + "≤")
    def print_b22(self):
        self.l1.setText(self.l1.text() + "≥")
    def print_b23(self):
        self.l1.setText(self.l1.text() + "∞")
    def print_b24(self):
        self.l1.setText(self.l1.text() + "!")
    def print_b25(self):
        self.l1.setText(self.l1.text() + "∴")
    def print_b26(self):
        self.l1.setText(self.l1.text() + "⇉")
    def print_b27(self):
        self.l1.setText(self.l1.text() + "±")
    def print_b28(self):
        self.l1.setText(self.l1.text() + "∩")
    def print_b29(self):
        self.l1.setText(self.l1.text() + "√")
    def print_b30(self):
        self.l1.setText(self.l1.text() + "∛")
    def print_b31(self):
        self.l1.setText(self.l1.text() + "∜")
    def print_b32(self):
        self.l1.setText(self.l1.text() + "x_y")
    def print_b33(self):
        self.l1.setText(self.l1.text() + "Σ")
    def print_b34(self):
        self.l1.setText(self.l1.text() + "¬")
    def print_b35(self):
        self.l1.setText(self.l1.text() + "∈")
    def print_b36(self):
        self.l1.setText(self.l1.text() + "∉")
    def print_b37(self):
        self.l1.setText(self.l1.text() + "⊂")
    def print_b38(self):
        self.l1.setText(self.l1.text() + "sin")
    def print_b39(self):
        self.l1.setText(self.l1.text() + "cos")
    def print_b40(self):
        self.l1.setText(self.l1.text() + "tan")
    def print_b41(self):
        self.l1.setText(self.l1.text() + "d/dx")
    def print_b42(self):
        self.l1.setText(self.l1.text() + "∂/∂x")
    def print_b43(self):
        self.l1.setText(self.l1.text() + "△")
    def print_b44(self):
        self.l1.setText(self.l1.text() + "∬")
    def print_b45(self):
        self.l1.setText(self.l1.text() + "∭")
    def print_b46(self):
        self.l1.setText(self.l1.text() + "→")
    def print_b47(self):
        self.l1.setText(self.l1.text() + "↔")
    def print_b48(self):
        self.l1.setText(self.l1.text() + "∀")
    def print_b49(self):
        self.l1.setText(self.l1.text() + "∃")
    def print_b50(self):
        self.l1.setText(self.l1.text() + "csc")
    def print_b51(self):
        self.l1.setText(self.l1.text() + "sec")
    def print_b52(self):
        self.l1.setText(self.l1.text() + "cot")
    def print_b53(self):
        self.l1.setText(self.l1.text() + "arcsin")
    def print_b54(self):
        self.l1.setText(self.l1.text() + "arccos")
    def print_b55(self):
        self.l1.setText(self.l1.text() + "arctan")
    def print_b56(self):
        self.l1.setText(self.l1.text() + "≡")
    def print_b57(self):
        self.l1.setText(self.l1.text() + "°")
    def print_b58(self):
        self.l1.setText(self.l1.text() + "∥")
    def print_b59(self):
        self.l1.setText(self.l1.text() + "⇌")
    def print_b60(self):
        self.l1.setText(self.l1.text() + "Π")
    def print_b61(self):
        self.l1.setText(self.l1.text() + "∪")
    def print_b62(self):
        self.l1.setText(self.l1.text() + "∫")
    def print_b63(self):
        self.l1.setText(self.l1.text() + "↑")
    def print_b64(self):
        self.l1.setText(self.l1.text() + "↓")
    def print_b65(self):
        self.l1.setText(self.l1.text() + "pH")
    def print_b66(self):
        self.l1.setText(self.l1.text() + "log")
    def print_b67(self):
        self.l1.setText(self.l1.text() + "ln")
    def print_b68(self):
        self.l1.setText(self.l1.text() + "Δ")
    def print_b69(self):
        self.l1.setText(self.l1.text() + "α")
    def print_b70(self):
        self.l1.setText(self.l1.text() + "β")
    def print_b71(self):
        self.l1.setText(self.l1.text() + "γ")
    def print_b72(self):
        self.l1.setText(self.l1.text() + "∝")
    def print_b73(self):
        self.l1.setText(self.l1.text() + "∠")
    def print_b74(self):
        self.l1.setText(self.l1.text() + "δ")
    def print_b75(self):
        self.l1.setText(self.l1.text() + "ε")
    def print_b76(self):
        self.l1.setText(self.l1.text() + "ζ")
    def print_b77(self):
        self.l1.setText(self.l1.text() + "η")
    def print_b78(self):
        self.l1.setText(self.l1.text() + "θ")
    def print_b79(self):
        self.l1.setText(self.l1.text() + "ι")
    def print_b80(self):
        self.l1.setText(self.l1.text() + "κ")
    def print_b81(self):
        self.l1.setText(self.l1.text() + "λ")
    def print_b82(self):
        self.l1.setText(self.l1.text() + "μ")
    def print_b83(self):
        self.l1.setText(self.l1.text() + "ν")
    def print_b84(self):
        self.l1.setText(self.l1.text() + "e")
    def print_b85(self):
        self.l1.setText(self.l1.text() + "π")
    def print_b86(self):
        self.l1.setText(self.l1.text() + "ξ")
    def print_b87(self):
        self.l1.setText(self.l1.text() + "ω")
    def print_b88(self):
        self.l1.setText(self.l1.text() + "σ")
    def print_b89(self):
        self.l1.setText(self.l1.text() + "τ")
    def print_b90(self):
        self.l1.setText(self.l1.text() + "υ")
    def print_b91(self):
        self.l1.setText(self.l1.text() + "φ")
    def print_b92(self):
        self.l1.setText(self.l1.text() + "Φ")
    def print_b93(self):
        self.l1.setText(self.l1.text() + "χ")
    def print_b94(self):
        self.l1.setText(self.l1.text() + "ψ")
    def print_b95(self):
        self.l1.setText(self.l1.text() + "Ω")
    def print_b96(self):
        self.l1.setText(self.l1.text() + "|")
    
    def start_backspace_timer(self):
        self.backspace_timer.start(500)
    def stop_backspace_timer(self):
        if self.backspace_timer.isActive():
            self.backspace()
        self.backspace_timer.stop()
    def backspace(self):
        current_text = self.l1.text()
        self.l1.setText(current_text[:-1])
    def clear_text(self):
        self.l1.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
